# Generated by Django 4.2.7 on 2023-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
                ("repassword", models.CharField(max_length=50)),
            ],
        ),
    ]
